/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypto;

import java.awt.datatransfer.*;
import java.awt.Toolkit;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.System.exit;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author angel
 */
public class RsaGUI extends javax.swing.JFrame {
    public Rsa cipher;
    /**
     * Creates new form RsaGUI
     */
    public RsaGUI() {
        initComponents();
        setTitle("RSA Cipher by Angel Garcia");
        decryptbut.setEnabled(false);
        encryptbut.setEnabled(false);
        msgtocrypt.setVisible(false);
        msgtodecr.setVisible(false);
        encrylabel.setVisible(false);
        messageencrypted.setVisible(false);
        keysbut.setVisible(false);
        declabel.setVisible(false);
        decryptmg.setVisible(false);
        clipboard.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        exitbut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        generatebut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tocrypt = new javax.swing.JTextArea();
        encryptbut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        todecrypt = new javax.swing.JTextArea();
        decryptbut = new javax.swing.JButton();
        keysbut = new javax.swing.JButton();
        msgtodecr = new javax.swing.JLabel();
        msgtocrypt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        encrylabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        messageencrypted = new javax.swing.JTextArea();
        firststep = new javax.swing.JLabel();
        clipboard = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        decryptmg = new javax.swing.JTextArea();
        declabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitbut.setText("Exit");
        exitbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutActionPerformed(evt);
            }
        });
        getContentPane().add(exitbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 737, 90, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        jLabel1.setText("  RSA CIPHER");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 13, 180, 53));

        generatebut.setText("Generate");
        generatebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebutActionPerformed(evt);
            }
        });
        getContentPane().add(generatebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 742, 87, 35));

        jLabel2.setText("Message to encrypt");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 73, -1, -1));

        tocrypt.setColumns(20);
        tocrypt.setRows(5);
        jScrollPane1.setViewportView(tocrypt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 96, 659, -1));

        encryptbut.setText("Encrypt");
        encryptbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptbutActionPerformed(evt);
            }
        });
        getContentPane().add(encryptbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 205, -1, -1));

        jLabel3.setText("Message to decrypt");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 416, -1, -1));

        todecrypt.setColumns(20);
        todecrypt.setRows(5);
        jScrollPane2.setViewportView(todecrypt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 439, 659, -1));

        decryptbut.setText("Decrypt");
        decryptbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptbutActionPerformed(evt);
            }
        });
        getContentPane().add(decryptbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 542, -1, -1));

        keysbut.setText("Save Keys");
        keysbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keysbutActionPerformed(evt);
            }
        });
        getContentPane().add(keysbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 742, 132, 35));

        msgtodecr.setText("You have to write a message to decrypt!");
        getContentPane().add(msgtodecr, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 546, 289, -1));

        msgtocrypt.setText("You have to write a message to encrypt!");
        getContentPane().add(msgtocrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 205, -1, -1));

        encrylabel.setText("Encrypted Message");

        messageencrypted.setColumns(20);
        messageencrypted.setRows(5);
        jScrollPane4.setViewportView(messageencrypted);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(encrylabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(encrylabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 243, -1, -1));

        firststep.setForeground(new java.awt.Color(244, 27, 27));
        firststep.setText("The first step is generate the keys! (Generate Button)");
        getContentPane().add(firststep, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 35, -1, -1));

        clipboard.setText("Copy to Cipboard");
        clipboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clipboardActionPerformed(evt);
            }
        });
        getContentPane().add(clipboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 378, -1, -1));

        decryptmg.setColumns(20);
        decryptmg.setRows(5);
        jScrollPane3.setViewportView(decryptmg);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 617, 659, -1));

        declabel.setText("Decrypted Message");
        getContentPane().add(declabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 594, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 30, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 780, 290, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbutActionPerformed
       exit(0);
    }//GEN-LAST:event_exitbutActionPerformed

    private void generatebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebutActionPerformed
        cipher=new Rsa();
        decryptbut.setEnabled(true);
        encryptbut.setEnabled(true);
        keysbut.setVisible(true);
        firststep.setVisible(false);
        clipboard.setVisible(true);
        clipboard.setEnabled(false);
        
    }//GEN-LAST:event_generatebutActionPerformed

    private void encryptbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptbutActionPerformed
        System.out.println(tocrypt.getText());
        if(tocrypt.getText().isEmpty())
            msgtocrypt.setVisible(true);
        else{
            msgtocrypt.setVisible(false);
            encrylabel.setVisible(true);
            messageencrypted.setVisible(true);
            messageencrypted.setText(cipher.encrypt(tocrypt.getText()).toString());
            tocrypt.setText("");
            clipboard.setEnabled(true);
        }
        
    }//GEN-LAST:event_encryptbutActionPerformed

    private void decryptbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptbutActionPerformed
        if(todecrypt.getText().isEmpty())
            msgtodecr.setVisible(true);
        else{
            msgtodecr.setVisible(false);
            declabel.setVisible(true);
            decryptmg.setVisible(true);
            decryptmg.setText(cipher.decrypt(new BigInteger(todecrypt.getText())));
        }
    }//GEN-LAST:event_decryptbutActionPerformed

    private void clipboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clipboardActionPerformed

        StringSelection stringSelection = new StringSelection(messageencrypted.getText());
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_clipboardActionPerformed

    private void keysbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keysbutActionPerformed
        File publ=new File("public.key");
        File priv=new File("private.key");
        FileWriter pwriter,privwriter;
        if(!publ.exists()){
            try {
                pwriter = new FileWriter(publ,true);
                privwriter=new FileWriter(priv,true);
                pwriter.write("Public Exponent: "+ cipher.getPublicKey().getExponent().toString()+ "\n"+ "Modulus: "+cipher.getPublicKey().getModulus().toString());
                privwriter.write("Private Exponent: "+ cipher.getPrivateKey().getExponent().toString()+ "\n"+ "Modulus: "+cipher.getPrivateKey().getModulus().toString());
                pwriter.close();
                privwriter.close();

            }  catch (IOException ex) {
                Logger.getLogger(RsaGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_keysbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RsaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RsaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RsaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RsaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RsaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clipboard;
    private javax.swing.JLabel declabel;
    private javax.swing.JButton decryptbut;
    private javax.swing.JTextArea decryptmg;
    private javax.swing.JLabel encrylabel;
    private javax.swing.JButton encryptbut;
    private javax.swing.JButton exitbut;
    private javax.swing.JLabel firststep;
    private javax.swing.JButton generatebut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton keysbut;
    private javax.swing.JTextArea messageencrypted;
    private javax.swing.JLabel msgtocrypt;
    private javax.swing.JLabel msgtodecr;
    private javax.swing.JTextArea tocrypt;
    private javax.swing.JTextArea todecrypt;
    // End of variables declaration//GEN-END:variables
}
